Update current wolenetz editor data
w3c/media-source pull request #333
Opened 2023-10-25 22:29 UTC by wolenetz

For now at least, I'm in two places: current and former editor lists. This seems to me to be the best way to show precise history of my associaton (previously Google, now a W3C Invited Expert). This change also updates my email to one that reaches me.

2023-10-25 22:37 UTC, wolenetz commented
@tidoust - For some reason, the ipr check is failing even though when I navigate to https://www.w3.org/groups/wg/media/join/, it shows "Warning You already joined this group".
Can you help me figure this out please?

2023-10-26 00:52 UTC, marcoscaceres commented on media-source-respec.html
> +      company: "Google Inc.", companyURL: "https://www.google.com/" },
Nah, don't bother... people change association all the time. 
```suggestion
```

2023-10-26 00:52 UTC, marcoscaceres commented on media-source-respec.html
> +      note: "W3C Invited Expert since September 2023",
```suggestion
      company: "W3C Invited Expert",
```

2023-10-26 00:52 UTC, marcoscaceres commented on media-source-respec.html
> +      { name: "Matthew Wolenetz",  mailto:"matt.wolenetz@gmail.com", url: "",
```suggestion
      { name: "Matthew Wolenetz",  mailto:"matt.wolenetz@gmail.com",
```

2023-10-26 00:53 UTC, marcoscaceres requested changes
Suggestions to reflect your current state.

2023-10-26 01:03 UTC, marcoscaceres commented
@wolenetz, just also want to confirm that you will continue as a Editor? Can we assign you tasks etc?

2023-10-26 01:39 UTC, wolenetz commented
> @wolenetz, just also want to confirm that you will continue as a Editor? Can we assign you tasks etc?

Yes, though be advised I have less time to devote to editing than in the past.

2023-10-26 01:51 UTC, wolenetz commented
> @wolenetz, just also want to confirm that you will continue as a Editor? Can we assign you tasks etc?

(Duplicating here in the review thread, yes, that is my intent. Be advised I have less time to edit than in the past.)

2023-10-26 06:30 UTC, tidoust commented
> @tidoust - For some reason, the ipr check is failing even though when I navigate to https://www.w3.org/groups/wg/media/join/, it shows "Warning You already joined this group". Can you help me figure this out please?

Now fixed. The IPR bot got confused because it still had your previous W3C account in its (long-standing) cache. Cache invalidation is hard ;)

2023-10-27 18:14 UTC, wolenetz commented
@tidoust and @marcoscaceres thanks for the reviews and for fixing the IPR bot. If this LGTY, I'll squash and merge it.

2023-10-27 19:30 UTC, chrisn approved these changes

2023-10-28 20:23 UTC, merged